version: '3'

services:
  nginx:
      image: nginx:1.15-alpine
      network_mode: 'host'
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./data:/etc/nginx/conf.d
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  boxer:
    build: .
    hostname: boxer
    command: npm start
    privileged: true
    working_dir: /ricc-project/ricc-app
    ports:
      - 4200:4200
    volumes:
      - ../../.:/ricc-project

