FROM node:10

RUN apt-get update

WORKDIR /ricc-project

RUN npm i -g @angular/cli
RUN npm install -g ng2-charts
RUN npm install -g chart.js
RUN npm install -g nativescript
RUN npm i -g @nativescript/schematics