version: '3'

services:
  ricc-app:
    container_name: ricc-app
    build: .
    command: npm start
    privileged: true
    working_dir: /ricc-project/ricc-app
    ports:
      - 4200:4200
      - 5037:5037
    volumes:
      - .:/ricc-project