FROM node:10

RUN apt-get update

WORKDIR /ricc-project

RUN npm i -g @angular/cli
RUN npm install -g --save-dev ng2-charts
RUN npm install -g --save-dev chart.js
RUN npm install -g nativescript
RUN npm i -g @nativescript/schematics