version: '3'

services:
  nginx:
      image: nginx:1.15-alpine
      ports:
        - "80:80"
        - "8001:8001"
        - "443:443"
      volumes:
        - ./data:/etc/nginx/conf.d
        - static_files:/usr/share/nginx/html/static/
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      depends_on:
        - boxer

  boxer:
    build: .
    command: npm start
    privileged: true
    working_dir: /ricc-project/ricc-app
    ports:
      - 4200:4200
    volumes:
      - .:/ricc-project
      - static_files:/ric-project/ricc-app/src